name: Cập nhật tên miền
on:
  push:
  schedule:
    - cron: "0 0 * * *"
jobs:
  run:
    name: Cập nhật tên miền
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Install cloudflared for DoH
        run: |
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /etc/apt/trusted.gpg.d/cloudflare.asc
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/cloudflare.asc] https://pkg.cloudflare.com/cloudflare-main/deb/ all main" | sudo tee /etc/apt/sources.list.d/cloudflare-main.list
          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Start cloudflared DNS over HTTPS
        run: |
          sudo cloudflared proxy-dns --address 127.0.0.1 --port 5053 --upstream https://1.1.1.1/dns-query &
          sleep 5

      - name: Configure DNS resolver to use cloudflared (DoH)
        run: |
          sudo bash -c "echo 'nameserver 127.0.0.1' > /etc/resolv.conf"

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: 3.11
          
      - name: Cập nhật tên miền 
        run: python main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate date 
        run: echo "DATE=$(date +%F)" >> $GITHUB_ENV
        
      - name: Commit tool 
        uses: EndBug/add-and-commit@v9.1.1
        with:
          add: 'dnr-lang-vi.json'
          default_author: github_actor 
          message: 'Cập nhật tên miền: ${{ env.DATE }}'
          push: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
